### ISSUE TITLE
代码拉下后跑不起来+1，麻烦楼主回复下 

### ISSUE THREAD

**Issue by chenhu0920** [wujiabk/zhaopinApp#2]

**Comment by Aemple** [comment]
可以到我的仓库查看  Pig-outsourcing  最近刚写好的肯定可以跑  可以的话也可以给个star

**Comment by wjaxian** [comment]
> _No description provided._

如果跑不起来，可以贴一下报错信息。
可能由于node版本问题，造成版本依赖发生的错误。

**Comment by wjaxian** [comment]
> _No description provided._

可以试试降级node版本，然后再跑跑看。

**Comment by CracKerMe** [comment]
./src/container/login/login.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Array.some (<anonymous>)
    at Array.forEach (<anonymous>)

**Comment by snowandmumu** [comment]
> ./src/container/login/login.js
> Module build failed: TypeError: Cannot read property 'type' of undefined
> at Array.some ()
> at Array.forEach ()

遇到了一样的问题，解决没？

**Comment by CracKerMe** [comment]
> > ./src/container/login/login.js
> > Module build failed: TypeError: Cannot read property 'type' of undefined
> > at Array.some ()
> > at Array.forEach ()
> 
> 遇到了一样的问题，解决没？

还没看他的代码呢

**Comment by wjaxian** [comment]
> > ./src/container/login/login.js
> > Module build failed: TypeError: Cannot read property 'type' of undefined
> > at Array.some ()
> > at Array.forEach ()
> 
> 遇到了一样的问题，解决没？

这个问题是修饰器报错，可能与某个依赖版本问题引起的，我这边正在解决。

**Comment by wjaxian** [comment]
> > ./src/container/login/login.js
> > Module build failed: TypeError: Cannot read property 'type' of undefined
> > at Array.some ()
> > at Array.forEach ()
> 
> 遇到了一样的问题，解决没？

我这边已经把整个项目依赖版本做了升级处理，请删除之前拉取的版本代码重新拉取仓库最新代码运行。
